stages:
  - build
  - deploy

broker-svc_build:
  stage: build
  script:
    - echo "Building the broker service"
    # Add your build commands here
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
      - 'broker-svc/broker/**/*'

broker-svc_deploy:
  stage: deploy
  script:
    - echo "Deploying the broker service"
    # Add your deployment commands here
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
      - 'broker-svc/broker/**/*'

