// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/grpasr/asonrythme/broker_svc/broker/internal/services/orderService (interfaces: IOrderService)

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	orderDTO "gitlab.com/grpasr/asonrythme/broker_svc/broker/internal/dto/orderDTO"
	json "gitlab.com/grpasr/common/errors/json"
)

// MockIOrderService is a mock of IOrderService interface.
type MockIOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockIOrderServiceMockRecorder
}

// MockIOrderServiceMockRecorder is the mock recorder for MockIOrderService.
type MockIOrderServiceMockRecorder struct {
	mock *MockIOrderService
}

// NewMockIOrderService creates a new mock instance.
func NewMockIOrderService(ctrl *gomock.Controller) *MockIOrderService {
	mock := &MockIOrderService{ctrl: ctrl}
	mock.recorder = &MockIOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOrderService) EXPECT() *MockIOrderServiceMockRecorder {
	return m.recorder
}

// OrderCreateService mocks base method.
func (m *MockIOrderService) OrderCreateService(arg0 orderDTO.Order) json.IError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderCreateService", arg0)
	ret0, _ := ret[0].(json.IError)
	return ret0
}

// OrderCreateService indicates an expected call of OrderCreateService.
func (mr *MockIOrderServiceMockRecorder) OrderCreateService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderCreateService", reflect.TypeOf((*MockIOrderService)(nil).OrderCreateService), arg0)
}

// OrderGetService mocks base method.
func (m *MockIOrderService) OrderGetService() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OrderGetService")
}

// OrderGetService indicates an expected call of OrderGetService.
func (mr *MockIOrderServiceMockRecorder) OrderGetService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderGetService", reflect.TypeOf((*MockIOrderService)(nil).OrderGetService))
}
