// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.1
// source: api/v1/brokerjwt/Brokerjwt.proto

package brokerjwt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Jwtoken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jwt string `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *Jwtoken) Reset() {
	*x = Jwtoken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jwtoken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwtoken) ProtoMessage() {}

func (x *Jwtoken) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwtoken.ProtoReflect.Descriptor instead.
func (*Jwtoken) Descriptor() ([]byte, []int) {
	return file_api_v1_brokerjwt_Brokerjwt_proto_rawDescGZIP(), []int{0}
}

func (x *Jwtoken) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type IsJwtokenOKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOk         bool   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	ResponseCode int32  `protobuf:"varint,2,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	Role         string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Svc          string `protobuf:"bytes,4,opt,name=svc,proto3" json:"svc,omitempty"`
	Scope        string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
}

func (x *IsJwtokenOKResponse) Reset() {
	*x = IsJwtokenOKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsJwtokenOKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsJwtokenOKResponse) ProtoMessage() {}

func (x *IsJwtokenOKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsJwtokenOKResponse.ProtoReflect.Descriptor instead.
func (*IsJwtokenOKResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_brokerjwt_Brokerjwt_proto_rawDescGZIP(), []int{1}
}

func (x *IsJwtokenOKResponse) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

func (x *IsJwtokenOKResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *IsJwtokenOKResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *IsJwtokenOKResponse) GetSvc() string {
	if x != nil {
		return x.Svc
	}
	return ""
}

func (x *IsJwtokenOKResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

var File_api_v1_brokerjwt_Brokerjwt_proto protoreflect.FileDescriptor

var file_api_v1_brokerjwt_Brokerjwt_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x6a,
	0x77, 0x74, 0x2f, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x6a, 0x77, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x76, 0x31, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x6a, 0x77, 0x74,
	0x22, 0x1b, 0x0a, 0x07, 0x4a, 0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6a,
	0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x8b, 0x01,
	0x0a, 0x13, 0x49, 0x73, 0x4a, 0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4f, 0x4b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x76, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x76, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x32, 0x5c, 0x0a, 0x11, 0x4a,
	0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x47, 0x0a, 0x0b, 0x49, 0x73, 0x4a, 0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4f, 0x4b, 0x12,
	0x15, 0x2e, 0x76, 0x31, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x6a, 0x77, 0x74, 0x2e, 0x4a,
	0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x21, 0x2e, 0x76, 0x31, 0x5f, 0x62, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x6a, 0x77, 0x74, 0x2e, 0x49, 0x73, 0x4a, 0x77, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x4f,
	0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x6a, 0x77, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_brokerjwt_Brokerjwt_proto_rawDescOnce sync.Once
	file_api_v1_brokerjwt_Brokerjwt_proto_rawDescData = file_api_v1_brokerjwt_Brokerjwt_proto_rawDesc
)

func file_api_v1_brokerjwt_Brokerjwt_proto_rawDescGZIP() []byte {
	file_api_v1_brokerjwt_Brokerjwt_proto_rawDescOnce.Do(func() {
		file_api_v1_brokerjwt_Brokerjwt_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_brokerjwt_Brokerjwt_proto_rawDescData)
	})
	return file_api_v1_brokerjwt_Brokerjwt_proto_rawDescData
}

var file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_brokerjwt_Brokerjwt_proto_goTypes = []interface{}{
	(*Jwtoken)(nil),             // 0: v1_brokerjwt.Jwtoken
	(*IsJwtokenOKResponse)(nil), // 1: v1_brokerjwt.IsJwtokenOKResponse
}
var file_api_v1_brokerjwt_Brokerjwt_proto_depIdxs = []int32{
	0, // 0: v1_brokerjwt.JwtokenManagement.IsJwtokenOK:input_type -> v1_brokerjwt.Jwtoken
	1, // 1: v1_brokerjwt.JwtokenManagement.IsJwtokenOK:output_type -> v1_brokerjwt.IsJwtokenOKResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_brokerjwt_Brokerjwt_proto_init() }
func file_api_v1_brokerjwt_Brokerjwt_proto_init() {
	if File_api_v1_brokerjwt_Brokerjwt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jwtoken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsJwtokenOKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_brokerjwt_Brokerjwt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_brokerjwt_Brokerjwt_proto_goTypes,
		DependencyIndexes: file_api_v1_brokerjwt_Brokerjwt_proto_depIdxs,
		MessageInfos:      file_api_v1_brokerjwt_Brokerjwt_proto_msgTypes,
	}.Build()
	File_api_v1_brokerjwt_Brokerjwt_proto = out.File
	file_api_v1_brokerjwt_Brokerjwt_proto_rawDesc = nil
	file_api_v1_brokerjwt_Brokerjwt_proto_goTypes = nil
	file_api_v1_brokerjwt_Brokerjwt_proto_depIdxs = nil
}
